### ISSUE TITLE
Feature request: Visualize area names

### ISSUE THREAD

**Issue by DavidBoman** [cedbossneo/openmower-gui#11]
The map.bag and also the WS-endpoint serving map-data have a name for each area. It would be great if theese are shown and even better if one could add/edit them! 

I'm using https://github.com/waffle-stomper/OpenMower/blob/bagman/utils/map/bagman.py to name and change order of the areas now but It's tricky to know which area has which position in t he list. 

(It would of course be even better if you could add some kind of (re-)ordering in the GUI :) )

**Comment by cedbossneo** [comment]
I have this in mind, it's part of a feature i want to implement which is choosing the area you want to mow.

**Comment by DavidBoman** [comment]
That's exactly what I want! I'd love to help out but my I have a very shallow frontend experience. I'm senior backend guy but when it comes to frontend I'm limited to fiddling around with Angular and I have no React experience at all... please tell me if there is anything I can help out with that is suitable for a total frontend noob :)
