### ISSUE TITLE
Map offset not saved

### ISSUE THREAD

**Issue by prigorus** [cedbossneo/openmower-gui#21]
X and Y offset for maps is not saved/applied. When I move the cursor for X for 2 meters, it moves the map, and then it jumps back to 0. This stopped working about a week ago.

**Comment by DavidBoman** [comment]
I have the same issue.

**Comment by wjcloudy** [comment]
Same issue here, as a workaround - if you move it, let it reset to zero and then refresh the page - the offset sticks

**Comment by cedbossneo** [comment]
Thx, it gives me good idea of the underlying issue
