### ISSUE TITLE
Cannot see containers

### ISSUE THREAD

**Issue by alexvaut** [cedbossneo/openmower-gui#3]
Very nice ! I already run it on my openmower it works fine except the container part. I can connect to podman socket with `--volume /run/podman/podman.sock:/run/podman/podman.sock --env DOCKER_HOST=unix:///run/podman/podman.sock`; I also added the label `project=openmower`  to the openmower container but the openmower container doesn't show up in the UI. it is just empty... Any idea what I'm missing ? There are no erros in the openmower-gui container. 

Command used:
```
sudo /usr/bin/podman run \
  --replace --detach --tty --privileged \
  --name openmower-gui \
  --network=host \
  --volume /run/podman/podman.sock:/run/podman/podman.sock \
  --volume /boot/openmower/mower_config.txt:/config/mower_config.sh \
  --env MOWER_CONFIG_FILE=/config/mower_config.sh \
  --env DOCKER_HOST=unix:///run/podman/podman.sock  \
  --env ROS_MASTER_URI=http://192.168.1.50:11311 \
  local/openmower-ui:latest
````

![image](https://github.com/cedbossneo/openmower-gui/assets/20702322/f2c62622-f2fa-473e-a261-bdc06b9cbca5)
![image](https://github.com/cedbossneo/openmower-gui/assets/20702322/4206c0fc-6e7b-4f2b-98f1-6f951950d761)

**Comment by cedbossneo** [comment]
You need two labels, project: openmower and app: openmower

**Comment by alexvaut** [comment]
It works, thank you !

**Comment by 2m** [comment]
I tried running `openmower-gui` using the command from the first comment, but I was not able to enter the map editing mode. The dots on the map path would not appear. Is there something else I need to do to run `openmower-gui`?

**Comment by alexvaut** [comment]
It was working fine for me.
For the container part, you need to add 2 labels app and project in openmower container:

```
ExecStart=/usr/bin/podman run --conmon-pidfile %t/container-openmower.pid --cidfile %t/container-openmower.ctr-id --cgroups=no-conmon \
...
  --label io.containers.autoupdate=registry \
  --label project=openmower \
  --label app=openmower \
  --env ROSOUT_DISABLE_FILE_LOGGING=True \
...
